### ISSUE TITLE
oppgradere blockcontent til portabletext

### ISSUE THREAD

**Issue by kmriise** [navikt/dp-sanity-cms#93]
brukte blockcontentpreview i produktsiden for å slenge det opp midlertidig
dette bør oppgraderes til portabletextpreview, som da må berikes med våre spesialkomponenter og marks, slik blockcontentpreview har blitt beriket tidligere

**Comment by Mikaila94** [comment]
https://github.com/navikt/dp-sanity-cms/pull/114
